nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/': ~

# NelmioCorsBundle Configuration
# nelmio_cors:
 #    defaults:
  #       allow_credentials: true
  #       allow_origin: []
  # #       allow_headers: []
   #      allow_methods: []
   #      expose_headers: []
   #      max_age: 0
    #     hosts: []
     #    origin_regex: false
   #  paths:
    #     '^/api/':
    #         allow_origin: ['*']
    #         allow_headers: ['Origin', 'Content-Type', 'X-Requested-With', 'Accept']
    #         allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
    #         max_age: 3600